language: python
sudo: true 
dist: trusty
python:
    - 3.6.6
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libjpeg-dev
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
script:
    - make github
